apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-p4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: p4
  template:
    metadata:
      labels: 
        app: p4
    spec:
      containers:
        - name: p4
          image: python:3.6-alpine
          ports:
            - containerPort: 3000
          command: ["sh", "-c", "while true; do echo running; sleep 30; done"]